/**
 * Icon registry. Only these icons ship in the bundle, which keeps the site fast.
 * To use a new icon: find its name at https://lucide.dev, import it below,
 * then add it to the map with a short key you can type in a config file.
 */
import {
  ArrowDownToLine,
  Activity,
  Box,
  ChartNoAxesCombined,
  FileText,
  Map,
  Search,
  ScanLine,
  SlidersHorizontal,
  Table2,
  Text,
  TrendingUp,
  Zap,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Braces,
  Brain,
  Briefcase,
  Check,
  ChevronDown,
  Clipboard,
  Clock,
  Code2,
  Database,
  ExternalLink,
  FileCode2,
  FileDown,
  FileX2,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderTree,
  GitCommitHorizontal,
  Github,
  GraduationCap,
  Home,
  Instagram,
  Layers,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  Moon,
  MousePointerClick,
  Phone,
  Plus,
  Send,
  Sparkles,
  Star,
  Sun,
  Target,
  TriangleAlert,
  User,
  X,
} from 'lucide-react'

export const icons = {
  arrowDown: ArrowDownToLine,
  api: Zap,
  chartDetailed: ChartNoAxesCombined,
  container: Box,
  map: Map,
  search: Search,
  scan: ScanLine,
  sliders: SlidersHorizontal,
  table: Table2,
  text: Text,
  trending: TrendingUp,
  python: Activity,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  braces: Braces,
  brain: Brain,
  briefcase: Briefcase,
  chart: BarChart3,
  check: Check,
  chevronDown: ChevronDown,
  clipboard: Clipboard,
  clock: Clock,
  code: Code2,
  database: Database,
  education: GraduationCap,
  externalLink: ExternalLink,
  file: FileCode2,
  fileText: FileText,
  fileDown: FileDown,
  fileMissing: FileX2,
  folder: Folder,
  folderGit: FolderGit2,
  folderOpen: FolderOpen,
  folderTree: FolderTree,
  github: Github,
  home: Home,
  instagram: Instagram,
  layers: Layers,
  linkedin: Linkedin,
  lock: Lock,
  mail: Mail,
  mapPin: MapPin,
  moon: Moon,
  phone: Phone,
  plus: Plus,
  pointer: MousePointerClick,
  send: Send,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  updated: GitCommitHorizontal,
  user: User,
  warning: TriangleAlert,
  x: X,
}

export default icons
